## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "blog-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

#disableKinds = ["taxonomy", "section"]
disableKinds = ["section"]

## -----------------------------------------------
## Analytics support
## -----------------------------------------------

#googleAnalytics: G-MEASUREMENT_ID
#swetrixAnalytics = "3UYKaHJP56by"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]
  #github = "https://github.com/caressofsteel/"
  #twitter = "https://twitter.com/caressofsteel_"
  email = "hello@waiq.technology"
  #instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  #telegram = "https://telegram.org"

[Params.asset]
additional_css = ["css/waiq.css"]
