## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Welcome to the #WAIQ Age"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "http://localhost:1313"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

#disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Analytics support
## -----------------------------------------------

#googleAnalytics: G-MEASUREMENT_ID
#swetrixAnalytics = "3UYKaHJP56by"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true
  #gated = true

[Params.social]

[Params.asset]
  additional_css = ["css/fontawesome-all.min.css","css/waiq.css"]
  additional_js = ["js/fontawesome-all.min.js"]
